branch-defaults:
  web_app:
    environment: PagerDutyStats-env
environment-defaults:
  PagerDutyStats-env:
    branch: null
    repository: null
global:
  application_name: pager_duty_stats
  default_ec2_keyname: null
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
